name: HuskHomesGUI
description: Fork of HomeGUI that works with HuskHomes
version: 1.0
main: com.technovision.HuskHomesGUI.HuskHomesGUI
api-version: 1.16
depend: [HuskHomes]
loadbefore: [HuskHomes]
authors: [TechnoVision, William278]
commands:
  home:
    description: Opens the home GUI
    usage: /home
    aliases: homes, homelist