name: HuskHomesGUI
description: Fork of HomeGUI that works with HuskHomes
version: 1.01
main: com.technovision.HuskHomesGUI.HuskHomesGUI
api-version: 1.16
depend: [HuskHomes]
authors: [TechnoVision, William278]