name: HuskHomesGUI
description: Fork of HomeGUI that works with HuskHomes
version: ${project.version}
main: com.technovision.HuskHomesGUI.HuskHomesGUI
api-version: 1.16
depend: [HuskHomes]
authors: [TechnoVision, William278]
