name: HuskHomesGUI
description: Fork of HomeGUI that works with HuskHomes
version: 1.0
main: com.technovision.HuskHomesGUI.HuskHomesGUI
api-version: 1.16
depend: [HuskHomes]
authors: [TechnoVision, William278]
commands:
  h:
    description: Opens the home GUI
    usage: /h
    aliases: [home, homes, homelist]